config/routes.rb
Rails.application.routes.draw do

  resources :uploads

  get 'uploads/create'

  get 'admin' => 'admin#index'
  get 'admin_permit' => 'admin#change_permit'

  root :to => "home#index"

  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end

  resources :projects do
    get 'search', on: :collection
  
    resources :comments
    resources :likes
  end

  resources :directory_semesters do
    resources :directory_classes
  end

  resources :directory_classes do
    resource :directory_homeworks
  end

  resources :directory_homeworks do
    resources :uploads do
      get "commit", on: :member
    end
    resources :projects do
      get "upper", on: :member
      get "branch", on: :member
      get "commit", on: :member
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  #validates :user_id, :presence => true
  #validates :project_id, :presence => true
end

app/models/directory_class.rb
class DirectoryClass < ActiveRecord::Base
  belongs_to :directory_semester
  has_many :directory_homeworks

  accepts_nested_attributes_for :directory_semester
end

app/models/directory_homework.rb
class DirectoryHomework < ActiveRecord::Base
	belongs_to :directory_class
	has_many :projects
end

app/models/directory_semester.rb
class DirectorySemester < ActiveRecord::Base
	has_many :directory_classes
end

app/models/homework.rb
class Homework < ActiveRecord::Base
  belongs_to :subject
  has_many :projects

  validates :name, :presence => true
  validates :subject_id, :presence => true
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  #validates :user_id, :presence => true
  #validates :project_id, :presence => true
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :directory_homework

	accepts_nested_attributes_for :directory_homework

	belongs_to :user
	has_many :comments, :dependent => :destroy
	has_many :likes, :dependent => :destroy
	belongs_to :project
	has_many :projects

	public	
		def self.search(query)
		    # where(:title, query) -> This would return an exact match of the query
		    where("project_name like ? OR description like ? OR user_name like ?", "%#{query}%", "%#{query}%", "%#{query}%")
		end

		def parent_id
			self.project_id
		end

		def is_root
			parent_id.nil?
		end

		def is_editable(current_user)
			current_user.id == self.user_id and Project.where(:project_id => self.id).all.count == 0
		end
end

app/models/semester.rb
class Semester < ActiveRecord::Base
	validates :name, :presence => true,
		:format => { with: /\A20[0-9]{2}\-[1-2]\Z/ }

	has_many :subjects
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :semester
  has_many :homeworks

  validates :name, :presence => true
  validates :semester_id, :presence => true
end

app/models/upload.rb
class Upload < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  has_many :projects

  validates :user_name, presence: true

 	validates :student_id, presence: true, length: {maximum: 10}, uniqueness: { case_sensitive: false }, format: { with: /\A[0-9]*\z/, message: "ID는 숫자만 입력할 수 있습니다." }

  validates :role, presence: true, format: { with: /(\Astudent\z|\Ata\z|\Aadmin\z)/ }
  devise :timeoutable, :timeout_in => 60.minutes
  attr_accessor :login

  def self.find_first_by_auth_conditions(warden_conditions)
  	conditions = warden_conditions.dup
  	if login = conditions.delete(:login)
    	where(conditions).where(["student_id = :value OR lower(email) = lower(:value)", { :value => login }]).first
  	else
    	where(conditions).first
  	end
	end

  def self.permit(user_id)
    user = User.find(user_id)
    
    if user
      user.permit = true
      user.save
      true
    else
      false
    end
  end

end

app/controllers/directory_homeworks_controller.rb
class DirectoryHomeworksController < ApplicationController
  before_action :set_directory_homework, only: [:show, :edit, :update, :destroy]
  before_filter :require_permit
  
  def index
    @directory_homeworks = DirectoryHomework.all

    #homeworks to show on #index view
  end

  def show
    @directory_homework = DirectoryHomework.find(params[:id])

    #find specific homework to show on view
  end

  def new
    @directory_homework = DirectoryHomework.new
    
  end

  def edit
    @directory_homework = DirectoryHomework.find(params[:id])

    #find specific homework to edit on view
    respond_to do |format|
      format.html #edit.html.erb
      format.xml { render :xml => @directory_homework }
    end
  end

  def create
    #directory_homework to create
    #directory_homework_params contains homework attributes

    @directory_class = DirectoryClass.find(params[:directory_class_id])
    @directory_homework = @directory_class.directory_homeworks.create(directory_homework_params)

    respond_to do |format|
      if @directory_homework.save
        format.html { redirect_to directory_class_path(@directory_class), notice: 'Directory created'}
      else
        format.html{ render action: "new"}  
      end
    end
  end

  def update
    #update edited homework
    
    @directory_homework.update(directory_homework_params)
  end

  def destroy
    #destroy specific homework

    @directory_homework.destroy
    respond_to do |format|
      if @directory_homework.destroy
        format.html { redirect_to directory_homework_path(@directory_homework), notices: "Directory destroyed"}
      else
        format.html{ render action: "new"}
      end
    end
  end

  private
    def set_directory_homework
      @directory_homework = DirectoryHomework.find(params[:id])
    end

    def directory_homework_params
      params.require(:directory_homework).permit(:class_name, :directory_class_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
	def devise_error_messages!
		return "" if resource.errors.empty?

		messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
	    sentence = I18n.t("errors.messages.not_saved",
	                      count: resource.errors.count,
	                      resource: resource.class.model_name.human.downcase)
	    html = <<-HTML

	    <div>
	      <br>
	      <ul>#{messages}</ul>	
	      
	    </div>
	    HTML
	    html.html_safe
	end
end

app/helpers/directory_homeworks_helper.rb
module DirectoryHomeworksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/directory_homeworks/_form.html.erb
<%= form_for(@directory_homework) do |f| %>
  <% if @directory_homework.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@directory_homework.errors.count, "error") %> prohibited this directory_homework from being saved:</h2>

      <ul>
      <% @directory_homework.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :class_name %><br>
    <%= f.text_field :class_name %>
  </div>
  <!--
  <div class="field">
    <%= f.label :directory_class_id %><br>
    <%= f.text_field :directory_class_id %>
  </div>
  -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/directory_homeworks/edit.html.erb
<h1>Editing directory_homework</h1>

<%= render 'form' %>

<%= link_to 'Show', @directory_homework %> |
<%= link_to 'Back', directory_homeworks_path %>

app/views/directory_homeworks/index.html.erb
<h1>Listing directory_homeworks</h1>

<table>
  <thead>
    <tr>
      <th>Class name</th>
      <th>Directory class</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @directory_homeworks.each do |directory_homework| %>
      <tr>
        <td><%= directory_homework.class_name %></td>
        <td><%= directory_homework.directory_class %></td>
        <td><%= link_to 'Show', directory_homework %></td>
        <td><%= link_to 'Edit', edit_directory_homework_path(directory_homework) %></td>
        <td><%= link_to 'Destroy', directory_homework, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Directory homework', new_directory_homework_path %>

app/views/directory_homeworks/new.html.erb
<h1>New directory_homework</h1>

<%= render 'form' %>

<%= link_to 'Back', directory_homeworks_path %>

app/views/directory_homeworks/show.html.erb
<p id="notice"><%= notice %></p>
<br><br>
<p>
  <strong>Homework name:</strong>
  <%= @directory_homework.class_name %>
</p>

<p>
<strong>Homeworks</strong>
<% @directory_homework.projects.each do |projects| %>
	<p>
		<b>homework name:</b>
		<%= projects.project_name %>	<!-- my mistake class_name....-->
	</p>
<% end %>
</p>

<h2> Add a projects:</h2>


<%= link_to 'Edit', edit_directory_homework_path(@directory_homework) %> |
<%= link_to 'Back', directory_semester_path(@directory_homework.directory_class_id) %>