config/routes.rb
Rails.application.routes.draw do

  resources :uploads

  get 'uploads/create'

  get 'admin' => 'admin#index'
  get 'admin_permit' => 'admin#change_permit'

  root :to => "home#index"

  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end

  resources :projects do
    get 'search', on: :collection
  
    resources :comments
    resources :likes
  end

  resources :directory_semesters do
    resources :directory_classes
  end

  resources :directory_classes do
    resource :directory_homeworks
  end

  resources :directory_homeworks do
    resources :uploads do
      get "commit", on: :member
    end
    resources :projects do
      get "upper", on: :member
      get "branch", on: :member
      get "commit", on: :member
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :directory_homework

	accepts_nested_attributes_for :directory_homework

	belongs_to :user
	has_many :comments, :dependent => :destroy
	has_many :likes, :dependent => :destroy
	belongs_to :project
	has_many :projects

	public	
		def self.search(query)
		    # where(:title, query) -> This would return an exact match of the query
		    where("project_name like ? OR description like ? OR user_name like ?", "%#{query}%", "%#{query}%", "%#{query}%")
		end

		def parent_id
			self.project_id
		end

		def is_root
			parent_id.nil?
		end

		def is_editable(current_user)
			current_user.id == self.user_id and Project.where(:project_id => self.id).all.count == 0
		end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include Transloadit::Rails::ParamsDecoder

  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_filter :require_permit

  def index
    @homework = DirectoryHomework.find(params[:directory_homework_id])
    @class = DirectoryClass.find(@homework.directory_class_id)
    @semester = DirectorySemester.find(@class.directory_semester_id)
    @projects = @homework.projects.where("project_id IS ?", nil).sort_by{|e| -e.likes.count } #project를 Like수에 따라 정렬하여 보여준다.
    @projects = Kaminari.paginate_array(@projects).page(params[:page]).per(5)
    @users = User.all
  end

  def upper
    @project = Project.find(params[:id])
    if @project.parent_id.nil?
      redirect_to directory_homework_projects_path
    else
      redirect_to branch_directory_homework_project_path(directory_homework_id:@project.directory_homework_id, id:@project.parent_id)
    end
  end
  def branch
    @project = Project.find(params[:id])
    @homework = DirectoryHomework.find(@project.directory_homework_id)
    @class = DirectoryClass.find(@homework.directory_class_id)
    @semester = DirectorySemester.find(@class.directory_semester_id)
    @user = User.find(@project.user_id)
    @branches = Project.where(:project_id => @project.id).all.sort_by{ |e| -e.likes.count } #project를 Like수에 따라 정렬하여 보여준다.
    @branches = Kaminari.paginate_array(@branches).page(params[:page]).per(5)
  end

  def commit
    load_directory_homework
    @parent = Project.find(params[:id])
    @file_url = params[:codefile_url]
    @project = @directory_homework.projects.new
  end

  def show
    load_directory_homework

    @class = DirectoryClass.find(@directory_homework.directory_class_id)
    @semester = DirectorySemester.find(@class.directory_semester_id)
    @project = Project.find(params[:id])
    @creator = User.find(@project.user_id)
    @parent = Project.find(@project.parent_id) unless @project.parent_id.nil?
    @content = CodeRay.scan(URI.parse(@project.codefile).read, set_format(@project.codefile)).div

    respond_to do |format|
      format.html
      format.xml { render :xml => @project }
    end
  end

  def upload
    #file_field = @params['form']['file'] rescue nil
    # file_field is a StringIO object
    #file_field.content_type # 'text/csv'
    #file_field.full_original_filename
  end

  def new
    load_directory_homework
    @project = @directory_homework.projects.new

    @file_url = params[:codefile_url]

  end

  def edit
    load_directory_homework
    @project = @directory_homework.projects.find(params[:id])
    #@project = Project.find(params[:id])
    @parent = @project.parent_id.nil? ? @directory_homework : Project.find(@project.parent_id)
    @file_url = @project.codefile
    respond_to do |format|
      format.html
      format.xml { render :xml => @project }
    end
  end

  def create
    load_directory_homework

    @project = @directory_homework.projects.new(project_params)
    @project.project_id = params[:project][:parent_id]
    @project.user_id = current_user.id
    @project.user_name = current_user.user_name

    respond_to do |format|
      if @project.save
        format.html { redirect_to [@directory_homework, @project], notice: 'Project created'}
      else
        format.html { render action: "new" }
      end
    end
  end

  def update
    load_directory_homework
    @project.update(project_params)
      if @project.save
        redirect_to directory_homework_project_path(@directory_homework, @project)
      else
        format.html { render action: "edit"}
    end
  end

  def destroy
    load_directory_homework
    respond_to do |format|
      if @project.destroy
        format.html { redirect_to directory_homework_projects_path(@directory_homework), notice: 'Project destroyed'}
      else
        format.html { render action: "new" }
      end
    end
  end

  def search
    if params[:search].length > 0
      @projects = Project.search(params[:search])
      @search = String.new(params[:search])
    else
      @projects = nil
    end 
  end

  private
    def load_directory_homework
      @directory_homework = DirectoryHomework.find(params[:directory_homework_id])
    end

    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:project_name, :description, :codefile)
    end

    def set_format(url)
      format = url.split(/.*\./)[1]
      if format == "rb"
        format = "ruby"
      elsif format == "py"
        format = "python"
      elsif format == "js"
        format = "javascript"
      end
      format
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<!--New 혹은 Commit시 입력하는 Form-->
<%= form_for([@directory_homework, @project], :html => {:multipart => true}) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% unless @file_url %>
    <br><br>
    <div class="panel panel-default">
      <div class="panel-body">
        먼저, 코드 파일을 등록하고 프로젝트 형식을 작성합니다.
        <% if @parent.nil? %>
          <%= link_to '코드 파일 첨부하기', new_upload_path(:dh_id => @directory_homework.id), :style=>"padding-left: 50px" %>
        <% else %>
          <%= link_to '코드 파일 첨부하기', commit_directory_homework_upload_path(@directory_homework.id, @parent.id), :style=>"padding-left: 50px"%>
        <% end %> 
      </div>
    </div>

  <% else %>
  <br><br>
  <div class="form-group" style="padding: 10px">
        <label for="project_name" class="col-lg-3 control-label">
          <font color = "green">프로젝트 이름</font>
        </label>
        <div class="col-lg-7">
          <input style="border-width:3px; border-style:solid; border-color: skyblue; auto; padding:0px;" id="project_name" name="project[project_name]" type="text" class="form-control" placeholder="프로젝트 이름 입력" value="<%=@project.project_name %>"/>
        </div>
      </div>
  <br>
  <div class="form-group" style="padding: 10px">
    <label for="project_name" class="col-lg-3 control-label">
      <font color = "green">파일 경로</font>
    </label>
    <div class="col-lg-7">
      <text style="border-width:3px; border-style:solid; border-color: skyblue; auto; padding:0px;" id="project-file" name="project[project_name]" type="text" class="form-control" >
        <%= @file_url %>
      </text>
    </div>
  </div>

  <div class="form-group">
    <div style = "padding:30px" class="col-lg-10">
          <textarea style="border-width:3px; border-style:solid; border-color: skyblue; auto; padding:10px;" rows = "10" cols = "15" id="description" name="project[description]" type="text_area" class="form-control" placeholder="프로젝트에 대한 설명을 작성 해 주세요. 첨부한 코드 파일에 대한 설명과 컴파일 방법 등을 자세하게 작성 해 주세요." value="<%=@project.description %>"></textarea>
    </div>

    <div class="form-group">
      <div class="col-lg-offset-3 col-lg-7 row-lg-2">
        <input class="btn btn-info btn-lg pull-right" name="commit" type="submit" value="업로드" style="font-size: 20px" margin-top = "20px" />
      </div>
    </div>

  <div class="invisible">
    <%= f.number_field :parent_id, :value => @parent.id if params.has_key?(:id) %>
    <%= f.text_field :codefile, :value => @file_url %>
  </div>

  <% end %>
<% end %>

app/views/projects/_pagination.html.erb
<% page_number = @projects.count/10 + 1 %>
<% for i in 1..page_number %>
<li><%= i %> </li>
<% end %> 

app/views/projects/_project.html.erb
<!-- 프로젝트 렌더링-->
<tr>
	<td>
		<div class="pull-right">
			<h6>
				<% @homework = DirectoryHomework.find(project.directory_homework_id) %>
				<% @class = DirectoryClass.find(@homework.directory_class_id) %>
				<% @semester = DirectorySemester.find(@class.directory_semester_id) %>
				<% @parent = Project.find(project.parent_id) unless project.parent_id.nil? %>

				<%= link_to @semester.semester_name, directory_semester_path(@semester) %> >
				<%= link_to @class.class_name, directory_class_path(@class) %> >
				<%= link_to @homework.class_name, directory_homework_projects_path(@homework)  %> >
				<%= link_to @parent.project_name, directory_homework_project_path(@homework, @parent) unless @parent.nil? %>	
			</h6>
		</div>
		<%= link_to project.project_name, directory_homework_project_path(@homework, project) %>
	</td>
</tr>

app/views/projects/branch.html.erb
<!-- 해당 프로젝트에 Commit된 프로젝트(하위 프로젝트)의 목록을 보여준다 -->
<div id="page-wrap" >
  <ol class="breadcrumb pull-right">
      <li class="active">
        <%= @project.project_name %>
      </li>
  </ol>

  <%= link_to @semester.semester_name, directory_semester_path(@semester) %> >
  <%= link_to @class.class_name, directory_class_path(@semester) %> >
  <%= link_to @homework.class_name, directory_homework_projects_path(@homework)  %>

  <h3>
    <%= @user.user_name%> / <%= link_to @project.project_name, directory_homework_project_path(@project.directory_homework_id, @project) %>
  </h3>
  <table class="table table-condensed">
    <% if @branches.empty? %>
      <br/><h5>프로젝트가 존재하지 않습니다.</h5>
    <% else %>
      <% @branches.each do |branch| %>
        <tr>
          <td><%= link_to branch.project_name, directory_homework_project_path(@project.directory_homework_id, branch) %>
          </td>
          <td>
            <div class="btn-group btn-group-xs">
              <% @project = branch %>
              <%= render 'likes/like' %>
            </div>
            <% @project = Project.find(branch.parent_id) %>
          </td>
          <% if branch.is_editable(current_user) %>
            <td>
              [<%= link_to 'Edit', edit_directory_homework_project_path(@project.directory_homework_id, branch) %>
              / <%= link_to 'Destroy', directory_homework_project_path(@project.directory_homework_id, branch), method: :delete, data: { confirm: 'Are you sure?' } %>]
            </td>
          <% end %>
        </tr>
      <% end %>
      <%= paginate @branches %>
    <% end%>
  </table>
  <br><%= link_to 'Commit', commit_directory_homework_project_path %>
</div>

app/views/projects/commit.html.erb
<!-- new와 마찬가지로 projects_controller의 create로 Parameter를 전달한다 -->
<!-- 상위 프로젝트의 ID를 유지하는 것 이외엔 같은 Logic이다.-->
<div id="page-wrap" >
	<h1>Commit to</h1>
	<%= @parent.project_name %>
	<%= render 'form' %>
</div>

app/views/projects/edit.html.erb
<h2>프로젝트 수정하기
	<span class="btn-group">
	      <%= button_to '취소', directory_homework_project_path(@directory_homework, @project), :class =>"btn btn-default", :method => "get" %>
	</span>
</h2>
<%= render 'form' %>

app/views/projects/index.html.erb
<!-- Homework의 프로젝트 목록을 나타내며, 최상위 프로젝트만 보여준다 -->
<div id="page-wrap" >
  <!--현재 Homework의 경로-->
  <ol class="breadcrumb pull-right">
    <li>
      <%= link_to @semester.semester_name, directory_semester_path(@semester) %>
    </li>
    <li>
      <%= link_to @class.class_name, directory_class_path(@class) %>
    </li>
    <li class="active">
      <%= @homework.class_name %>
    </li>
  </ol>

  <h3>프로젝트 목록</h3>
    <table class="table table-condensed">
      <% unless @projects.empty? %>
        <% @projects.each do |project| %>
          <tr>
            <td><%= link_to project.project_name, directory_homework_project_path(@homework, project) %></td>
            <td>
              Like: <%= project.likes.count %>
            </td>
          </tr>
        <% end %>
    </table>
    <%= paginate @projects %>
    <% else %>
        <br/><h5>프로젝트가 존재하지 않습니다.</h5>
    <% end %>
  <br>
  <%= link_to '프로젝트 등록', new_directory_homework_project_path, :class => "btn btn-primary" %>
</div>

app/views/projects/new.html.erb
<!-- 최상위 프로젝트 생성시 보여주는 View -->
<div id="page-wrap" >
	<h1>프로젝트 만들기</h1>
	<%= render 'form' %>	<!--projects/form의 내용을 그린다-->
</div>

app/views/projects/search.html.erb
<!-- 검색 결과를 보여주는 View -->
<div id="page-wrap">
<h2> <font color = "sky blue"> <%= @search %> </font> 에 대한 검색 결과입니다.</h2>
  <table class="table table-condensed">
      <%= render(@projects) %>
  </table>
</div>

app/views/projects/show.html.erb
<div id="page-wrap-project" style="background-color: white">
  <div id="page-wrap" style="background-color: white">
    <p id="notice"></p>

  <div class="row">
    <!--화면 상단의 학기 > 과목 > 숙제 를 나타내는 부분 -->
    <div class="pull-left">
      <%= link_to @semester.semester_name, directory_semester_path(@semester) %> >
      <%= link_to @class.class_name, directory_class_path(@class) %> >
      <%= link_to @directory_homework.class_name, directory_homework_projects_path(@directory_homework)  %> >
      <%= link_to @parent.project_name, directory_homework_project_path(@parent.directory_homework_id, @parent) unless @parent.nil?%>
    </div>

    <div class="row" style="display:inline">
      <h3>
        <!--프로젝트 이름, 수정, 삭제 버튼-->
        <%= @creator.user_name%> /
        <strong><%= @project.project_name %></strong>
        <% if @project.is_editable(current_user) %>
          <span class="btn-group">
          <%= button_to '수정', edit_directory_homework_project_path(@directory_homework, @project), :class =>"btn btn-default btn-xs", :method => "get" %>
          </span>
          <span class="btn-group">
          <%= button_to '삭제', directory_homework_project_path(@directory_homework, @project), :class =>"btn btn-default btn-xs", :method => :delete, data: { confirm: '삭제하시겠습니까?' } %>
          </span>
        <% end %>
        <!-- 상위 프로젝트, 하위 프로젝트, Like를 표시하는 부분-->
        <div class="btn-toolbar pull-right" >
          <div class="btn-group">
            <%= button_to "상위 프로젝트", upper_directory_homework_project_path, :class => "btn btn-info", :method => "get" %>
          </div>
          <div class="btn-group">
            <%= button_to "하위 프로젝트", branch_directory_homework_project_path, :class => "btn btn-success", :method => "get" %> 
          </div>
          <div class="btn-group">
            <%= render 'likes/like' %> 
          </div>
      </h3>
    </div>

    <!--업로드된 코드를 보여주는 부분-->
    <div class="panel panel-default">
      <div class="panel-body">
        /<%= @project.codefile.split(/.*\//)[1] %>
        <%= link_to "코드 저장", @project.codefile, :class => "pull-right" %>
      </div>

      <div class="panel-footer">
        <a href='javascript:void(0)' onclick="this.innerHTML=(this.nextSibling.style.display=='none')?'감추기':'코드 보기';this.nextSibling.style.display=(this.nextSibling.style.display=='none')?'block':'none'";>코드 보기</a><DIV style='display:none'>
          <br>
            <% format = @project.codefile.split(/.*\./)[1] %>
            <% if format == "rb" %>
              <% format = "ruby" %>
            <% elsif format == "py" %>
              <% format = "python" %>
            <% end %>
            
            <% if ["c", "cpp", "ruby", "python", "css", "erb", "html", "php", "xml", "yaml", "json", "java", "javascript", "sql"].include? format.downcase %>
              <%= render html: @content.html_safe %>
            <% else %>
              지원하지 않는 형식입니다.
            <% end %>
        </DIV>
      </div>
    </h3>
    </div>

    <div class="well" style="padding-bottom: 20px">
      <!-- 코드에 대한 설명-->
      <h3><strong>README</strong></h3>
      <br><%= @project.description %>
    </div>
    <!-- 댓글 구현 -->
    <div class="row">
      <h3>댓글</h3>
      <div class="col-md-12">
        <table class="table">
            <%= render @project.comments.sort_by{ |c| c.created_at } %>
        </table>
        <%= render "comments/form" %><br/><br/>
      </div>
    </div>
  </div>
</div>