config/routes.rb
Rails.application.routes.draw do

  resources :uploads

  get 'uploads/create'

  get 'admin' => 'admin#index'
  get 'admin_permit' => 'admin#change_permit'

  root :to => "home#index"

  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end

  resources :projects do
    get 'search', on: :collection
  
    resources :comments
    resources :likes
  end

  resources :directory_semesters do
    resources :directory_classes
  end

  resources :directory_classes do
    resource :directory_homeworks
  end

  resources :directory_homeworks do
    resources :uploads do
      get "commit", on: :member
    end
    resources :projects do
      get "upper", on: :member
      get "branch", on: :member
      get "commit", on: :member
    end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  #validates :user_id, :presence => true
  #validates :project_id, :presence => true
end

app/models/directory_class.rb
class DirectoryClass < ActiveRecord::Base
  belongs_to :directory_semester
  has_many :directory_homeworks

  accepts_nested_attributes_for :directory_semester
end

app/models/directory_homework.rb
class DirectoryHomework < ActiveRecord::Base
	belongs_to :directory_class
	has_many :projects
end

app/models/directory_semester.rb
class DirectorySemester < ActiveRecord::Base
	has_many :directory_classes
end

app/models/homework.rb
class Homework < ActiveRecord::Base
  belongs_to :subject
  has_many :projects

  validates :name, :presence => true
  validates :subject_id, :presence => true
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  #validates :user_id, :presence => true
  #validates :project_id, :presence => true
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :directory_homework

	accepts_nested_attributes_for :directory_homework

	belongs_to :user
	has_many :comments, :dependent => :destroy
	has_many :likes, :dependent => :destroy
	belongs_to :project
	has_many :projects

	public	
		def self.search(query)
		    # where(:title, query) -> This would return an exact match of the query
		    where("project_name like ? OR description like ? OR user_name like ?", "%#{query}%", "%#{query}%", "%#{query}%")
		end

		def parent_id
			self.project_id
		end

		def is_root
			parent_id.nil?
		end

		def is_editable(current_user)
			current_user.id == self.user_id and Project.where(:project_id => self.id).all.count == 0
		end
end

app/models/semester.rb
class Semester < ActiveRecord::Base
	validates :name, :presence => true,
		:format => { with: /\A20[0-9]{2}\-[1-2]\Z/ }

	has_many :subjects
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :semester
  has_many :homeworks

  validates :name, :presence => true
  validates :semester_id, :presence => true
end

app/models/upload.rb
class Upload < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  has_many :projects

  validates :user_name, presence: true

 	validates :student_id, presence: true, length: {maximum: 10}, uniqueness: { case_sensitive: false }, format: { with: /\A[0-9]*\z/, message: "ID는 숫자만 입력할 수 있습니다." }

  validates :role, presence: true, format: { with: /(\Astudent\z|\Ata\z|\Aadmin\z)/ }
  devise :timeoutable, :timeout_in => 60.minutes
  attr_accessor :login

  def self.find_first_by_auth_conditions(warden_conditions)
  	conditions = warden_conditions.dup
  	if login = conditions.delete(:login)
    	where(conditions).where(["student_id = :value OR lower(email) = lower(:value)", { :value => login }]).first
  	else
    	where(conditions).first
  	end
	end

  def self.permit(user_id)
    user = User.find(user_id)
    
    if user
      user.permit = true
      user.save
      true
    else
      false
    end
  end

end

app/controllers/directory_semesters_controller.rb
class DirectorySemestersController < ApplicationController
  before_action :set_directory_semester, only: [:show, :edit, :update, :destroy]
  before_filter :require_permit
  
  def index
    @directory_semesters = DirectorySemester.all
    #semesters to show on #index view
  end

  def show
    @directory_semester = DirectorySemester.find(params[:id])
    #find specific semester to show on view
  end

  def new
    @directory_semester = DirectorySemester.new
  end

  def edit
    @directory_semester = DirectorySemester.find(params[:id])

    #find specific semester to edit
    respond_to do |format|
      format.html #edit.html.erb
      format.xml { render :xml => @directory_semester }
    end
  end

  def create
    #create new semester, directory_semester_params contains semester attributes
    @directory_semester = DirectorySemester.new(directory_semester_params)
    respond_to do |format|
      if @directory_semester.save
        format.html { redirect_to root_path, notice: 'Directory created'}
      else
        format.html{ render action: "new"}
      end
    end
  end

  def update

    #update semester with new attributes, directory_semester_params contains semester attributes
    @directory_semester.update(directory_semester_params)
    respond_to do |format|
      if @directory_semester.save
        format.html { redirect_to directory_semester_path(@directory_semester), notice: 'Directory updated'}
      else
       format.html { render action: "edit"} 
      end
    end
  end

  def destroy

    #destroy specific semester
    @directory_semester.destroy
    respond_to do |format|
      if @directory_semester.destroy
        format.html { redirect_to root_path, notices: "Directory destroyed"}
      else
        format.html{ render action: "new"}
      end
    end
  end

  private
    def set_directory_semester
      @directory_semester = DirectorySemester.find(params[:id])
    end

    def directory_semester_params
      params.require(:directory_semester).permit(:semester_name)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
	def devise_error_messages!
		return "" if resource.errors.empty?

		messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
	    sentence = I18n.t("errors.messages.not_saved",
	                      count: resource.errors.count,
	                      resource: resource.class.model_name.human.downcase)
	    html = <<-HTML

	    <div>
	      <br>
	      <ul>#{messages}</ul>	
	      
	    </div>
	    HTML
	    html.html_safe
	end
end

app/helpers/directory_semesters_helper.rb
module DirectorySemestersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homeworks_helper.rb
module HomeworksHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/uploads_helper.rb
module UploadsHelper
end

app/views/directory_semesters/_form.html.erb
<!--
<%= form_for(@directory_semester) do |f| %>
  <% if @directory_semester.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@directory_semester.errors.count, "error") %> prohibited this directory_semester from being saved:</h2>

      <ul>
      <% @directory_semester.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= f.label :semester_name %><br>
    <%= f.text_field :semester_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
-->
  <div id = "page_wrap">
        <%= form_for(@directory_semester) do |f| %>
          <p>
          <%= f.label '과목 이름' %><br>
          <%= f.text_field :semester_name %>
         <%= f.submit 'NEW', :class => 'btn btn-info' %>
        </p>
        <% end %>
  </div>

app/views/directory_semesters/edit.html.erb
<h1>Editing directory_semester</h1>

<%= render 'form' %>

<%= link_to 'Show', @directory_semester %> |
<%= link_to 'Back', directory_semesters_path %>

app/views/directory_semesters/index.html.erb
  <h2>Semesters</h2>
  <table class="table table-condensed">
    <% @directory_semesters.each do |semesters| %>
      <tr>
        <td><%= link_to semesters.semester_name, directory_semester_path(semesters) %></td>
        <td>[<%= link_to 'Edit', edit_directory_semester_path(semesters) %>
        / <%= link_to 'Destroy', semesters, method: :delete, data: { confirm: 'Are you sure?' } %>]</td>
      </tr>
    <% end %>
  </table>

  <br><br><br>

  <% if current_user.role == "admin" %>
    <div class="well well-sm pull-right">
      <%= form_for :directory_semester do |f| %>
        <p>
          <%= f.label '학기이름' %><br>
          <%= f.text_field :semester_name %>
          <%= f.submit 'NEW', :class=> 'btn btn-info'%>
        </p>
      <% end %>
    </div>
  <% end %>

app/views/directory_semesters/new.html.erb
<div class="col-md-10">
<h1>학기 생성하기</h1>

<%= render 'form' %>

</div>

app/views/directory_semesters/show.html.erb
<body>
  <div id="page-wrap" >
  <br>
  <ol class="breadcrumb pull-right">
    <li class="active">
      <%= @directory_semester.semester_name %>
    </li>
  </ol>

  <h2>Classes</h2>
  <table class="table table-condensed">
    <% @directory_semester.directory_classes.each do |classes| %>
      <tr>
 	      <td><%= link_to classes.class_name, directory_class_path(classes) %></td>
        <!-- <td>[<%= link_to 'Edit', edit_directory_class_path(classes) %>
		    / <%= link_to 'Destroy', classes, method: :delete, data: { confirm: 'Are you sure?' } %>]</td> -->
      </tr>
    <% end %>
  </table>

  <br><br><br>

    <%if current_user.role == "admin" %>
      <div class="well well-sm pull-right">
        <%= form_for([@directory_semester, @directory_semester.directory_classes.build]) do |f| %>
          <p>
          <%= f.label '과목 이름' %><br>
          <%= f.text_field :class_name %>
         <%= f.submit 'NEW', :class => 'btn btn-info' %>
        </p>
        <% end %>
      </div>
    <% end%>
  </div>
<body>